spring.application.name=calidad
server.port=8083

# Configuración R2DBC para MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3306/calidadProyecto
spring.r2dbc.username=root
spring.r2dbc.password=guillermo

# Swagger
springdoc.swagger-ui.path=/swagger-ui-custom.html
